apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: df-pv
spec:
  version: {{ .TagName }}
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/yashbhutwala/kubectl-df-pv/releases/download/{{ .TagName }}/kubectl-df-pv_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "df-pv"
      to: "."
    - from: "LICENSE"
      to: "."
    bin: "df-pv"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/yashbhutwala/kubectl-df-pv/releases/download/{{ .TagName }}/kubectl-df-pv_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: "df-pv"
      to: "."
    - from: "LICENSE"
      to: "."
    bin: "df-pv"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/yashbhutwala/kubectl-df-pv/releases/download/{{ .TagName }}/kubectl-df-pv_{{ .TagName }}_windows_amd64.zip" .TagName }}
    files:
    - from: "df-pv.exe"
      to: "."
    - from: "LICENSE"
      to: "."
    bin: "df-pv.exe"
  shortDescription: Show disk usage (like unix df) for persistent volumes
  homepage: https://github.com/yashbhutwala/kubectl-df-pv
  description: |
    This plugin emulates Unix style df for persistent volumes.
